# Generated by Django 4.2.6 on 2025-03-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='feeling',
            field=models.CharField(blank=True, choices=[('Excited', 'Excited'), ('Determined', 'Determined'), ('Drained', 'Drained'), ('Motivated', 'Motivated'), ('Accomplished', 'Accomplished'), ('Down', 'Down'), ('Tired', 'Tired')], max_length=200, null=True),
        ),
    ]
